### PR TITLE
Rendered piece images.

### PR DESCRIPTION
**Pull request by MelsenC**
Now the piece images show up on the board.

### CODE REVIEW

**Comment by dennisgit42** [comment]
Drag and drop movement of pieces does not work for when moving piece images since the current javascript selects the  tag and not the <span> that is the parent of each .

**Comment by MelsenC** [comment]
I noticed this, too. Could we fix by changing how Javascript selects the element? It definitely breaks when I add the img tag. It still works when I simply use the string image name.

**Comment by MelsenC** [comment]
Dennis, I don't need you to do more work on this if it isn't something you're already intimately familiar with, from being the one to set up this drag and drop functionality.

**Comment by dennisgit42** [comment]
Please look at my own branch for this, pieceimages . I fixed the problems created by using img tag instead of span and now both moving and capturing pieces causes the piece images to update correctly. Please tell me if you find any other issues. [https://github.com/Infinite-Loops-Firehose/chess/tree/pieceimages](url)

**Comment by dennisgit42** [comment]
Or just see my new pull request PieceImages

**Pull request merged**
